# Generated by Django 3.1.2 on 2020-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
    ]
